apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-ms-payments
  namespace: cx-ayala-dev
  labels:
    app: cu-ms-payments
    depto: pagos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu-ms-payments
  template:
    metadata:
      labels:
        app: cu-ms-payments
    spec:
      containers:
      - name: hola-mundo
        image: cxayala/cu-ms-payments:{{ imageTag }}
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        envFrom:
            - configMapRef:
                name: cu-ms-payments
            - secretRef:
                name: cu-ms-payments
        volumeMounts:
            - name: config
              mountPath: /app/config
        startupProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: cu-ms-payments-config
---
apiVersion: v1
kind: Service
metadata:
  name: cu-ms-payments-svc
  namespace: cx-ayala-dev
spec:
  selector:
    app: cu-ms-payments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cu-ms-payments
  namespace: cx-ayala-dev
data:
  LOG_LEVEL: debug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cu-ms-payments-config
  namespace: cx-ayala-dev
data:
  app.conf: |
    server {
      port 1000
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: cu-ms-payments
  namespace: cx-ayala-dev
data:
  DATABASE_PASSWORD: U3VwZXJTZWd1cm8yMDI1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cu-ms-payments
  namespace: cx-ayala-dev
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: cu-ms-payments
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization ##en base a porcentaje de uso
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
